name: Rutinal TrackStack Health Check

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  Health_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://trackstack-c9rh.onrender.com
          max-attempts: 3
          retry-delay: 5s
